### ISSUE TITLE
Please fix development target

### ISSUE THREAD

**Issue by michaelhoefer** [Malax/rust-cnb-starter#2]
https://github.com/Malax/rust-cnb-starter/blob/70e638e1d3c8d12d0135d38277380fec396465bb/Makefile.toml#L77

This autofails, since target/buildpack does not exist initially. 

```
let destination = PathBuf::from("target/buildpack");

if destination.exists() {
    std::fs::remove_dir_all(&destination).unwrap();
}

fs::create_dir_all(&destination.join("bin")).unwrap();
```

**Comment by Malax** [comment]
Fixed with 8b04adb, thanks! 👍🏻
